// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZGaWE3bqKkLfwulG8fJ1rNW2FZjArEQ',
    appId: '1:1047636452234:web:3a4d4d318472ae24609e73',
    messagingSenderId: '1047636452234',
    projectId: 'contact-crud-13e44',
    authDomain: 'contact-crud-13e44.firebaseapp.com',
    storageBucket: 'contact-crud-13e44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtgygKJ_j6a2nauscfO_Zl6GMvtyvShI',
    appId: '1:1047636452234:android:632fccbc67947fbe609e73',
    messagingSenderId: '1047636452234',
    projectId: 'contact-crud-13e44',
    storageBucket: 'contact-crud-13e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7O3rPSgLtoDTZoywz6M45VSo8l6oaeI',
    appId: '1:1047636452234:ios:6ff0950f8e14a3e7609e73',
    messagingSenderId: '1047636452234',
    projectId: 'contact-crud-13e44',
    storageBucket: 'contact-crud-13e44.appspot.com',
    iosClientId: '1047636452234-h9l7qptq1fuc1p2lmre3pt415kqol60i.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7O3rPSgLtoDTZoywz6M45VSo8l6oaeI',
    appId: '1:1047636452234:ios:6ff0950f8e14a3e7609e73',
    messagingSenderId: '1047636452234',
    projectId: 'contact-crud-13e44',
    storageBucket: 'contact-crud-13e44.appspot.com',
    iosClientId: '1047636452234-h9l7qptq1fuc1p2lmre3pt415kqol60i.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );
}
