// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe35CICiAR-j9F819msEB5Baw9c1xFKP8',
    appId: '1:322936128339:web:33bfcef64a14086cb397a6',
    messagingSenderId: '322936128339',
    projectId: 'pts-login-7a2c1',
    authDomain: 'pts-login-7a2c1.firebaseapp.com',
    storageBucket: 'pts-login-7a2c1.appspot.com',
    measurementId: 'G-ZC03GBENE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2cywQtpIyLAd3_wRETDV3Q7bgU27I4s',
    appId: '1:322936128339:android:4b271e1019ec50eeb397a6',
    messagingSenderId: '322936128339',
    projectId: 'pts-login-7a2c1',
    storageBucket: 'pts-login-7a2c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDijP-EbUdxHuXYZxY4QydnRvi4hnchcYc',
    appId: '1:322936128339:ios:57b99711c3b7030bb397a6',
    messagingSenderId: '322936128339',
    projectId: 'pts-login-7a2c1',
    storageBucket: 'pts-login-7a2c1.appspot.com',
    iosClientId: '322936128339-k7tskrbbfuc6n2mekp8cddbg66tderff.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDijP-EbUdxHuXYZxY4QydnRvi4hnchcYc',
    appId: '1:322936128339:ios:57b99711c3b7030bb397a6',
    messagingSenderId: '322936128339',
    projectId: 'pts-login-7a2c1',
    storageBucket: 'pts-login-7a2c1.appspot.com',
    iosClientId: '322936128339-k7tskrbbfuc6n2mekp8cddbg66tderff.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateManagement',
  );
}
